language: groovy
jdk:
- oraclejdk7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # if we run on the same box as previous build, make sure target is clean
  - rm -rf target
script: ./grailsw refresh-dependencies --non-interactive
  && ./grailsw test-app --non-interactive
  && ./grailsw package-plugin --non-interactive
